Add SkipBody and SkipResBody functions to Config. it used to skip record "body" and "resBody" fields when write log.
gofiber/contrib pull request #158
Opened 2022-04-22 06:32 UTC by piyongcai

* Add SkipBody and SkipResBody functions to Config. it used to skip record "body" and "resBody" fields when write log.

// SkipBody defines a function to skip log  "body" field when returned true.
//
// Optional. Default: nil
SkipBody func(c *fiber.Ctx) bool

// Next dSkipBody defines a function to skip log  "resBody" field when returned true.
//
// Optional. Default: nil
SkipResBody func(c *fiber.Ctx) bool

2022-04-22 06:39 UTC, ReneWerner87 requested changes
please add tests that test the new parts that have been added

2022-04-22 06:40 UTC, ReneWerner87 commented on fiberzap/config.go
> +	// Next dSkipBody defines a function to skip log  "resBody" field when returned true.
"dSkipBody" -> SkipBody

2022-04-22 07:09 UTC, piyongcai commented
> please add tests that test the new parts that have been added

Add Test for SkipBody and SkipResBody config item.

2022-04-22 07:23 UTC, piyongcai commented on fiberzap/config.go
> +	// Next dSkipBody defines a function to skip log  "resBody" field when returned true.
fixed comment "dSkipBody" -> SkipBody

2022-05-18 06:35 UTC, ReneWerner87 commented
@piyongcai sorry for my late reply

would merge the pull request, please only expand the readme in the fiber zap folder with the new possibilities of configuration

2022-05-24 06:03 UTC, ReneWerner87 commented
@piyongcai

2022-07-07 05:54 UTC, ReneWerner87 approved these changes

2022-07-07 05:54 UTC, merged

2023-01-10 08:12 UTC, piyongcai commented
> @piyongcai

sorry，i missing this pr.

2023-01-10 08:13 UTC, piyongcai commented
@ReneWerner87 
sorry, i missing this pr,  because some reason....