OPA middleware enhancement proposal
gofiber/contrib pull request #273
Opened 2022-08-30 13:27 UTC by Joffref

Signed-off-by: Mathis Joffre <mariusjoffre@gmail.com>

2022-09-07 13:25 UTC, ReneWerner87 requested changes
thanks for the work 
though we miss test, the readme adjustment and a bit more information about the reason for the adjustment so that everyone who finds this pull request knows what happened here

2022-09-08 19:16 UTC, mstrYoda requested changes

2022-09-08 19:16 UTC, mstrYoda commented on opafiber/fiber.go
> +		input, err = cfg.InputCreationMethod(c)
No need for `input := make(map[string]interface{})` line.

`input, err := cfg.InputCreationMethod(c)` already covers it.

2022-09-08 19:16 UTC, mstrYoda commented on opafiber/fiber.go
> +		headers := make(map[string]string)
It creates a map even if the user does not include headers? I think the "if" condition should remain, WDYT @ReneWerner87 @efectn ?

2022-09-09 08:47 UTC, mstrYoda commented
LGTM

2022-09-09 09:07 UTC, ReneWerner87 approved these changes

2022-09-09 09:09 UTC, Joffref commented
Do you want me to squash my commits ? @ReneWerner87

2022-09-09 09:14 UTC, merged

2022-09-09 10:07 UTC, ReneWerner87 commented
> Do you want that I squash my commits ? @ReneWerner87

no not really needed