:sparkles: Add fiberi18n middleware
gofiber/contrib pull request #373
Opened 2022-11-21 20:16 UTC by Skyenought

Add middleware to [go-i18n](https://github.com/nicksnyder/go-i18n) support for Fiber.

### Quick Start
```go
func main() {
	app := fiber.New()
	app.Use(
		fiberi18n.New(&fiberi18n.Config{
			RootPath:        "./localize",
			AcceptLanguages: []language.Tag{language.Chinese, language.English},
			DefaultLanguage: language.Chinese,
		}),
	)
	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString(fiberi18n.MustGetMessage("welcome"))
	})
	app.Get("/:name", func(ctx *fiber.Ctx) error {
		return ctx.SendString(fiberi18n.MustGetMessage(&i18n.LocalizeConfig{
			MessageID: "welcomeWithName",
			TemplateData: map[string]string{
				"name": ctx.Params("name"),
			},
		}))
	})
	app.Listen("127.0.0.1:3000")
}

```

2022-11-22 12:51 UTC, gaby requested changes
Can you add an entry in .github/dependabot.yml for this middleware?

2022-11-22 13:09 UTC, Skyenought commented
> Can you add an entry in .github/dependabot.yml for this middleware?

ok

2022-12-08 07:45 UTC, ReneWerner87 commented
@Skyenought

2022-12-11 16:53 UTC, ReneWerner87 requested changes
Is there a reason why you have not updated the security yaml ? have you only read half the comment ? 

https://github.com/gofiber/contrib/blob/main/.github/workflows/security.yml

2022-12-11 17:03 UTC, Skyenought commented
Sorry!

2022-12-11 17:04 UTC, gaby commented
@Skyenought Can you update the go.mod to 1.18 and run `go mod tidy`

2022-12-11 17:07 UTC, Skyenought commented
> @Skyenought Can you update the go.mod to 1.18 and run `go mod tidy`

ok

2022-12-11 17:17 UTC, gaby commented
@Skyenought For some reason its pointing to fiber 2.39.x, latest should be 2.40.1 l. May need to run `go get -u ./...`

2022-12-12 09:52 UTC, ReneWerner87 approved these changes

2022-12-12 09:53 UTC, ReneWerner87 commented
@Skyenought pls check 
![image](https://user-images.githubusercontent.com/7063188/207015420-99c609bc-5f8c-4fbc-8d94-62d1d599a193.png)

2022-12-13 05:22 UTC, Skyenought commented
Strangely enough, I couldn't figure out what went wrong

2023-01-02 12:23 UTC, ReneWerner87 commented
@Skyenought any progress ?

2023-01-03 03:51 UTC, Skyenought commented
I recently got COVID-19, so not much progress, sorry.

2023-02-04 18:04 UTC, gaby commented
@Skyenought Can you run `go test -cover ./...`, what's the current coverage % for this middleware?

2023-02-04 18:05 UTC, Skyenought commented
> go test -cover ./...

ok      github.com/gofiber/contrib/fiberi18n    0.684s  coverage: 77.5% of statements
?       github.com/gofiber/contrib/fiberi18n/example    [no test files]

2023-03-14 18:51 UTC, ReneWerner87 commented
@Skyenought can you please update the middleware and check the workflows, when the workflows are running and the documentation is there i will merge it right away

2023-03-15 00:31 UTC, Skyenought commented
> @Skyenought can you please update the middleware and check the workflows, when the workflows are running and the documentation is there i will merge it right away

Get

2023-03-15 10:28 UTC, ReneWerner87 commented
@Skyenought i think the changes in the root readme.md and the release drafter workflow+config files are missing

2023-03-15 13:05 UTC, efectn approved these changes

2023-03-15 13:13 UTC, gaby approved these changes
LGTM

2023-03-15 15:03 UTC, Skyenought commented on fiberi18n/go.sum
> +github.com/BurntSushi/toml v1.0.0 h1:dtDWrepsVPfW9H/4y7dDgFc2MBUSeJhlaDtK13CxFlU=
GET

2023-03-19 14:17 UTC, gaby commented
@ReneWerner87 I think this is good to merge now.

2023-03-19 14:18 UTC, ReneWerner87 commented
Ok will merge it tomorrow morning

2023-03-20 07:17 UTC, merged

2023-03-20 07:18 UTC, Skyenought commented
@ReneWerner87 Thanks!

2023-03-20 07:20 UTC, ReneWerner87 commented
https://github.com/gofiber/contrib/releases/tag/fiberi18n%2Fv0.1.0 
thx for the effort