Add GetResBody to Config
gofiber/contrib pull request #421
Opened 2023-01-08 08:18 UTC by piyongcai

When use compress middleware, resBody is unreadable. 
You can set GetResBody func to get readable resBody.
![fiberzap](https://user-images.githubusercontent.com/54696/211186803-0b7a15c9-aac4-4b1b-9e36-d5267605d3c5.png)

2023-01-10 03:41 UTC, piyongcai commented
@ReneWerner87 
?

2023-01-10 06:16 UTC, gaby requested changes
Can you update the unit-tests to test for this?

2023-01-10 06:32 UTC, efectn commented
we should add default uncompression options instead of making it nil

2023-01-10 08:06 UTC, piyongcai commented
> Can you update the unit-tests to test for this?

added: Test_GetResBody

2023-01-10 09:17 UTC, piyongcai commented
> we should add default uncompression options instead of making it nil

There are many ways to change resbody except compress middleware

2023-01-10 14:56 UTC, efectn approved these changes

2023-01-10 14:59 UTC, gaby approved these changes
Looks good!

2023-01-13 07:41 UTC, ReneWerner87 commented
@piyongcai please add something for your new feature in the readme.md

2023-01-13 07:42 UTC, ReneWerner87 commented
after that I will merge it immediately

2023-01-16 07:20 UTC, ReneWerner87 commented
@piyongcai check my last comment

2023-01-28 06:56 UTC, piyongcai commented
> @piyongcai check my last comment
@ReneWerner87
sorry, Because my grandfather died,  the job is have to be done late.

2023-01-28 08:24 UTC, ReneWerner87 commented
Oh I am sorry to hear that
My condolences

2023-01-30 07:52 UTC, merged